
#
# Config.
#

url: http://blog.andyjiang.com
writeKey: 425safDNzgGhWwGte2oSmvBDQLrTSycN

#
# Bio.
#

name: Andy Jiang
role: Derp Engineer

#
# Social.
#

twitter: andyjiang
github: lambtron
linkedin: andyjiang

#
# Theme.
#

theme: lambtron/plato-snowball
token: 793380c2b217b28771705da53eb4b596a0a2d110
